
print("hello python")
print('####################################')
print('welcome to the network automation')
print('######################################')
print("Hello Python")
print("#" * 36)
print("Welcome to the Network Automation")
print("#" * 36)
banner = "#" * 36
print(banner)
print("Hello Python")
print("Welcome to the Network Automation")
print(banner)
print('=' * 50)
print('Network automation toolkit')
print("version  : 1.0")
print('author   : Aslam')
print('current date  : 4-8-2026')
print("welcome to network automation learning series")
print('=' * 50)